:: Generated by: https://github.com/swagger-api/swagger-codegen.git
::

@echo off

dotnet restore src\CashLockedUpFunds
dotnet build src\CashLockedUpFunds
echo Now, run the following to start the project: dotnet run -p src\CashLockedUpFunds\CashLockedUpFunds.csproj --launch-profile web.
echo.
