/*
 * Cash Locked Up Funds
 *
 * Cash Locked Up Funds
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace CashLockedUpFunds.Models
{ 
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class CashLockedUpRequest : IEquatable<CashLockedUpRequest>
    { 
        /// <summary>
        /// Gets or Sets EntityId
        /// </summary>
        [DataMember(Name="entityId")]
        public int? EntityId { get; set; }

        /// <summary>
        /// Gets or Sets TrustAccountId
        /// </summary>
        [DataMember(Name="trustAccountId")]
        public int? TrustAccountId { get; set; }

        /// <summary>
        /// Gets or Sets Currency
        /// </summary>
        [DataMember(Name="currency")]
        public string Currency { get; set; }

        /// <summary>
        /// Gets or Sets Amount
        /// </summary>
        [DataMember(Name="amount")]
        public decimal? Amount { get; set; }

        /// <summary>
        /// Gets or Sets LockedUpUntil
        /// </summary>
        [DataMember(Name="lockedUpUntil")]
        public string LockedUpUntil { get; set; }

        /// <summary>
        /// Gets or Sets Reference
        /// </summary>
        [DataMember(Name="reference")]
        public string Reference { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class CashLockedUpRequest {\n");
            sb.Append("  EntityId: ").Append(EntityId).Append("\n");
            sb.Append("  TrustAccountId: ").Append(TrustAccountId).Append("\n");
            sb.Append("  Currency: ").Append(Currency).Append("\n");
            sb.Append("  Amount: ").Append(Amount).Append("\n");
            sb.Append("  LockedUpUntil: ").Append(LockedUpUntil).Append("\n");
            sb.Append("  Reference: ").Append(Reference).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((CashLockedUpRequest)obj);
        }

        /// <summary>
        /// Returns true if CashLockedUpRequest instances are equal
        /// </summary>
        /// <param name="other">Instance of CashLockedUpRequest to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(CashLockedUpRequest other)
        {
            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    EntityId == other.EntityId ||
                    EntityId != null &&
                    EntityId.Equals(other.EntityId)
                ) && 
                (
                    TrustAccountId == other.TrustAccountId ||
                    TrustAccountId != null &&
                    TrustAccountId.Equals(other.TrustAccountId)
                ) && 
                (
                    Currency == other.Currency ||
                    Currency != null &&
                    Currency.Equals(other.Currency)
                ) && 
                (
                    Amount == other.Amount ||
                    Amount != null &&
                    Amount.Equals(other.Amount)
                ) && 
                (
                    LockedUpUntil == other.LockedUpUntil ||
                    LockedUpUntil != null &&
                    LockedUpUntil.Equals(other.LockedUpUntil)
                ) && 
                (
                    Reference == other.Reference ||
                    Reference != null &&
                    Reference.Equals(other.Reference)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (EntityId != null)
                    hashCode = hashCode * 59 + EntityId.GetHashCode();
                    if (TrustAccountId != null)
                    hashCode = hashCode * 59 + TrustAccountId.GetHashCode();
                    if (Currency != null)
                    hashCode = hashCode * 59 + Currency.GetHashCode();
                    if (Amount != null)
                    hashCode = hashCode * 59 + Amount.GetHashCode();
                    if (LockedUpUntil != null)
                    hashCode = hashCode * 59 + LockedUpUntil.GetHashCode();
                    if (Reference != null)
                    hashCode = hashCode * 59 + Reference.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(CashLockedUpRequest left, CashLockedUpRequest right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(CashLockedUpRequest left, CashLockedUpRequest right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
