/*
 * Cash Locked Up Funds
 *
 * Cash Locked Up Funds
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace CashLockedUpFunds.Models
{ 
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class CashLockedUpWithdrawableRequest : IEquatable<CashLockedUpWithdrawableRequest>
    { 
        /// <summary>
        /// Gets or Sets NavByAccounts
        /// </summary>
        [DataMember(Name="nav-by-accounts")]
        public string NavByAccounts { get; set; }

        /// <summary>
        /// Gets or Sets ExchangeRates
        /// </summary>
        [DataMember(Name="exchange-rates")]
        public string ExchangeRates { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class CashLockedUpWithdrawableRequest {\n");
            sb.Append("  NavByAccounts: ").Append(NavByAccounts).Append("\n");
            sb.Append("  ExchangeRates: ").Append(ExchangeRates).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((CashLockedUpWithdrawableRequest)obj);
        }

        /// <summary>
        /// Returns true if CashLockedUpWithdrawableRequest instances are equal
        /// </summary>
        /// <param name="other">Instance of CashLockedUpWithdrawableRequest to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(CashLockedUpWithdrawableRequest other)
        {
            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    NavByAccounts == other.NavByAccounts ||
                    NavByAccounts != null &&
                    NavByAccounts.Equals(other.NavByAccounts)
                ) && 
                (
                    ExchangeRates == other.ExchangeRates ||
                    ExchangeRates != null &&
                    ExchangeRates.Equals(other.ExchangeRates)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (NavByAccounts != null)
                    hashCode = hashCode * 59 + NavByAccounts.GetHashCode();
                    if (ExchangeRates != null)
                    hashCode = hashCode * 59 + ExchangeRates.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(CashLockedUpWithdrawableRequest left, CashLockedUpWithdrawableRequest right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(CashLockedUpWithdrawableRequest left, CashLockedUpWithdrawableRequest right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
